[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 1  # Lower value optimizes for deployment cost
# via_ir = true       # Enable IR-based code generation
bytecode_hash = "none"  # Reduces bytecode size by removing metadata hash
cbor_metadata = false   # Disables CBOR metadata

# Advanced optimizer settings
[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdest_remover = true
order_literals = true
deduplicate = true
cse = true
constant_optimizer = true
yul = true
yul_details = { stackAllocation = true, optimizerSteps = "dhfoDgvulfnTUtnIf" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
